# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f82cead7ffc6a1aaaa9f9b9922cdd913c6520b769198f1f38cebccbee3bff7792a6329abfd2d7f9c9895dd9230ae8117b5d3045edfc8cb27c55eff78d04d007

test:
  secret_key_base: 91a0c774c1b9a5216d45683d7b9a0f8b2464da5a92ebada3a6390c351466047d198cb1cfa4338e2f66aabbb0d63565dbbda70aedfb9d31cd9b00e336b3235ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
